"""Well-known port reference data for the Vantage Reference Library."""

# risk: "high" | "med" | "low"
# proto: "TCP" | "UDP" | "TCP/UDP"
# tags: list of category strings used for filtering
# tools: Vantage generator slugs relevant to this port
# notes: short pentest tip

PORTS = [
    # ── FTP ─────────────────────────────────────────────────────────────────────
    {"port": 20, "proto": "TCP", "service": "FTP Data", "risk": "high",
     "tags": ["file-transfer"],
     "desc": "FTP data transfer channel (active mode).",
     "tools": ["nmap"],
     "notes": "Active FTP data channel. Usually filtered by modern firewalls."},
    {"port": 21, "proto": "TCP", "service": "FTP", "risk": "high",
     "tags": ["file-transfer"],
     "desc": "File Transfer Protocol — command channel. Credentials sent in plaintext.",
     "tools": ["nmap", "hydra", "medusa"],
     "notes": "Check for anonymous login, banner grabbing for version, writeable dirs."},

    # ── SSH / Telnet ────────────────────────────────────────────────────────────
    {"port": 22, "proto": "TCP", "service": "SSH", "risk": "med",
     "tags": ["remote-access"],
     "desc": "Secure Shell — encrypted remote access and tunneling.",
     "tools": ["nmap", "hydra", "medusa"],
     "notes": "Enumerate supported algorithms, check for weak keys. Brute-force with password list."},
    {"port": 23, "proto": "TCP", "service": "Telnet", "risk": "high",
     "tags": ["remote-access"],
     "desc": "Telnet — unencrypted remote terminal. Legacy protocol, rarely justified.",
     "tools": ["nmap", "hydra"],
     "notes": "Cleartext credentials. Try default creds. Presence is usually a finding by itself."},

    # ── Email ────────────────────────────────────────────────────────────────────
    {"port": 25, "proto": "TCP", "service": "SMTP", "risk": "med",
     "tags": ["email"],
     "desc": "Simple Mail Transfer Protocol — server-to-server mail relay.",
     "tools": ["nmap"],
     "notes": "Check for open relay (VRFY/EXPN commands). STARTTLS support via testssl."},
    {"port": 110, "proto": "TCP", "service": "POP3", "risk": "high",
     "tags": ["email"],
     "desc": "Post Office Protocol v3 — mail retrieval, plaintext.",
     "tools": ["nmap", "hydra"],
     "notes": "Credentials in cleartext unless STLS is used. Brute-force username/password."},
    {"port": 143, "proto": "TCP", "service": "IMAP", "risk": "high",
     "tags": ["email"],
     "desc": "Internet Message Access Protocol — mail sync, plaintext unless STARTTLS.",
     "tools": ["nmap", "hydra"],
     "notes": "Check STARTTLS support. Credential spray common against Office365-exposed IMAP."},
    {"port": 465, "proto": "TCP", "service": "SMTPS", "risk": "low",
     "tags": ["email"],
     "desc": "SMTP over SSL/TLS (legacy). Modern submission uses port 587.",
     "tools": ["nmap", "testssl"],
     "notes": "Run testssl for cipher strength and certificate issues."},
    {"port": 587, "proto": "TCP", "service": "SMTP Submission", "risk": "med",
     "tags": ["email"],
     "desc": "Email submission with STARTTLS — standard for MUAs sending mail.",
     "tools": ["nmap", "testssl"],
     "notes": "Check for open relay after STARTTLS negotiation."},
    {"port": 993, "proto": "TCP", "service": "IMAPS", "risk": "low",
     "tags": ["email"],
     "desc": "IMAP over TLS — encrypted mail sync.",
     "tools": ["nmap", "testssl", "hydra"],
     "notes": "Audit TLS config. Credential spray if auth is exposed."},
    {"port": 995, "proto": "TCP", "service": "POP3S", "risk": "low",
     "tags": ["email"],
     "desc": "POP3 over TLS.",
     "tools": ["nmap", "testssl"],
     "notes": "Verify certificate validity and TLS version."},

    # ── DNS ──────────────────────────────────────────────────────────────────────
    {"port": 53, "proto": "TCP/UDP", "service": "DNS", "risk": "med",
     "tags": ["dns", "network"],
     "desc": "Domain Name System — name resolution. UDP for queries, TCP for zone transfers.",
     "tools": ["nmap", "dnsrecon"],
     "notes": "Test for zone transfer (AXFR) via TCP. Enumerate subdomains. Check for DNSSEC."},

    # ── DHCP / TFTP ──────────────────────────────────────────────────────────────
    {"port": 67, "proto": "UDP", "service": "DHCP Server", "risk": "high",
     "tags": ["network"],
     "desc": "Dynamic Host Configuration Protocol — server listens here.",
     "tools": ["nmap", "responder"],
     "notes": "Rogue DHCP server attack can redirect DNS and gateway. Responder can exploit this."},
    {"port": 68, "proto": "UDP", "service": "DHCP Client", "risk": "low",
     "tags": ["network"],
     "desc": "DHCP client receives offers on this port.",
     "tools": ["nmap"],
     "notes": "Typically not targeted directly; rogue DHCP server impacts clients."},
    {"port": 69, "proto": "UDP", "service": "TFTP", "risk": "high",
     "tags": ["file-transfer"],
     "desc": "Trivial FTP — no authentication, often used for PXE boot and firmware.",
     "tools": ["nmap"],
     "notes": "No auth! Common on embedded devices and PXE servers. Try reading config files."},

    # ── HTTP / HTTPS ─────────────────────────────────────────────────────────────
    {"port": 80, "proto": "TCP", "service": "HTTP", "risk": "high",
     "tags": ["web"],
     "desc": "Hypertext Transfer Protocol — unencrypted web traffic.",
     "tools": ["nmap", "httpx", "gobuster", "ffuf", "nikto", "nuclei", "whatweb", "wafw00f", "dalfox", "sqlmap"],
     "notes": "Full web audit: fingerprint → content discovery → vuln scan. Check for redirect to HTTPS."},
    {"port": 443, "proto": "TCP", "service": "HTTPS", "risk": "high",
     "tags": ["web"],
     "desc": "HTTP over TLS — encrypted web. Same attack surface as 80, plus TLS issues.",
     "tools": ["nmap", "httpx", "gobuster", "ffuf", "nikto", "nuclei", "testssl", "whatweb", "wafw00f", "dalfox", "sqlmap"],
     "notes": "Run testssl for certificate/cipher issues in addition to full web audit."},
    {"port": 8080, "proto": "TCP", "service": "HTTP Alternate", "risk": "high",
     "tags": ["web"],
     "desc": "Common alternate HTTP port used by app servers, proxies, and dev servers.",
     "tools": ["nmap", "httpx", "gobuster", "ffuf", "nikto", "nuclei"],
     "notes": "Often less hardened than port 80. Check for admin panels and internal apps."},
    {"port": 8443, "proto": "TCP", "service": "HTTPS Alternate", "risk": "high",
     "tags": ["web"],
     "desc": "Alternate HTTPS used by app servers (Tomcat, WebLogic, etc.).",
     "tools": ["nmap", "httpx", "gobuster", "ffuf", "nikto", "testssl", "nuclei"],
     "notes": "Common for Jenkins, Tomcat manager, Kubernetes dashboard."},
    {"port": 8888, "proto": "TCP", "service": "Jupyter Notebook", "risk": "high",
     "tags": ["web", "rce"],
     "desc": "Default Jupyter Notebook/Lab port. Often exposed without auth in dev environments.",
     "tools": ["nmap", "httpx", "nuclei"],
     "notes": "Unauthenticated Jupyter = instant RCE via notebook execution. High value target."},

    # ── Kerberos ─────────────────────────────────────────────────────────────────
    {"port": 88, "proto": "TCP/UDP", "service": "Kerberos", "risk": "high",
     "tags": ["auth", "active-directory"],
     "desc": "Kerberos authentication — core of Active Directory.",
     "tools": ["nmap", "kerbrute", "getuserspns"],
     "notes": "AS-REP roasting (users without preauth), Kerberoasting (SPN accounts). Use kerbrute for user enum."},

    # ── RPC / NetBIOS / SMB ──────────────────────────────────────────────────────
    {"port": 111, "proto": "TCP/UDP", "service": "RPC Portmapper", "risk": "high",
     "tags": ["network", "rpc"],
     "desc": "ONC RPC portmapper — tells clients which port RPC services use.",
     "tools": ["nmap"],
     "notes": "Enumerate RPC services. Leads to NFS enumeration. Use `rpcinfo -p`."},
    {"port": 135, "proto": "TCP", "service": "MS-RPC", "risk": "high",
     "tags": ["windows", "rpc"],
     "desc": "Microsoft RPC endpoint mapper. Entry point for DCOM and WMI.",
     "tools": ["nmap", "netexec"],
     "notes": "Required for WMI/DCOM. Exploitable (MS03-026). Enumerate with rpcdump."},
    {"port": 137, "proto": "UDP", "service": "NetBIOS-NS", "risk": "high",
     "tags": ["windows", "file-transfer"],
     "desc": "NetBIOS Name Service — legacy Windows name resolution.",
     "tools": ["nmap", "responder", "enum4linux-ng"],
     "notes": "Responder can capture NTLMv2 hashes by responding to NBT-NS queries."},
    {"port": 138, "proto": "UDP", "service": "NetBIOS-DGM", "risk": "med",
     "tags": ["windows"],
     "desc": "NetBIOS datagram service — connectionless.",
     "tools": ["nmap"],
     "notes": "Usually present alongside 137/139. Enumerate with enum4linux-ng."},
    {"port": 139, "proto": "TCP", "service": "NetBIOS-SSN", "risk": "high",
     "tags": ["windows", "file-transfer"],
     "desc": "NetBIOS session service — older SMB over NetBIOS.",
     "tools": ["nmap", "netexec", "enum4linux-ng"],
     "notes": "Older SMB path. Use enum4linux-ng for full Windows enumeration."},
    {"port": 445, "proto": "TCP", "service": "SMB", "risk": "high",
     "tags": ["windows", "file-transfer", "active-directory"],
     "desc": "Server Message Block — Windows file sharing and named pipes. Rich attack surface.",
     "tools": ["nmap", "netexec", "enum4linux-ng", "secretsdump"],
     "notes": "EternalBlue (MS17-010), PetitPotam, null session enum, credential relay. Always enumerate."},
    {"port": 593, "proto": "TCP", "service": "RPC over HTTP", "risk": "med",
     "tags": ["windows", "rpc"],
     "desc": "MS-RPC over HTTP — allows RPC through HTTP proxies.",
     "tools": ["nmap"],
     "notes": "Used by Exchange and Outlook Anywhere. Can expose MAPI endpoints."},

    # ── LDAP ─────────────────────────────────────────────────────────────────────
    {"port": 389, "proto": "TCP/UDP", "service": "LDAP", "risk": "high",
     "tags": ["auth", "active-directory"],
     "desc": "Lightweight Directory Access Protocol — directory services, core of AD.",
     "tools": ["nmap", "netexec", "bloodhound-py"],
     "notes": "Anonymous bind often enabled. Enumerate users, groups, policies. BloodHound ingestion."},
    {"port": 636, "proto": "TCP", "service": "LDAPS", "risk": "med",
     "tags": ["auth", "active-directory"],
     "desc": "LDAP over SSL/TLS.",
     "tools": ["nmap", "netexec", "testssl", "bloodhound-py"],
     "notes": "Check certificate. Anonymous bind over TLS still possible."},
    {"port": 3268, "proto": "TCP", "service": "LDAP Global Catalog", "risk": "high",
     "tags": ["auth", "active-directory"],
     "desc": "Active Directory Global Catalog — forest-wide LDAP queries.",
     "tools": ["nmap", "bloodhound-py", "netexec"],
     "notes": "Confirms you're talking to a DC. BloodHound uses this for cross-domain data."},
    {"port": 3269, "proto": "TCP", "service": "LDAPS Global Catalog", "risk": "med",
     "tags": ["auth", "active-directory"],
     "desc": "AD Global Catalog over TLS.",
     "tools": ["nmap", "bloodhound-py"],
     "notes": "TLS version of 3268. Same attack surface."},

    # ── SNMP ─────────────────────────────────────────────────────────────────────
    {"port": 161, "proto": "UDP", "service": "SNMP", "risk": "high",
     "tags": ["monitoring", "network"],
     "desc": "Simple Network Management Protocol — device management and monitoring.",
     "tools": ["nmap"],
     "notes": "Default community strings `public`/`private`. v1/v2c cleartext. Can dump full config."},
    {"port": 162, "proto": "UDP", "service": "SNMP Trap", "risk": "low",
     "tags": ["monitoring", "network"],
     "desc": "SNMP trap receiver — devices send alerts here.",
     "tools": ["nmap"],
     "notes": "Less useful for offense; may receive verbose network state."},

    # ── NTP / Syslog / Finger ────────────────────────────────────────────────────
    {"port": 123, "proto": "UDP", "service": "NTP", "risk": "low",
     "tags": ["network"],
     "desc": "Network Time Protocol — clock synchronization.",
     "tools": ["nmap"],
     "notes": "monlist command (CVE-2013-5211) enables DoS amplification on older versions."},
    {"port": 514, "proto": "UDP", "service": "Syslog", "risk": "med",
     "tags": ["monitoring"],
     "desc": "Legacy syslog — unauthenticated, cleartext log forwarding.",
     "tools": ["nmap"],
     "notes": "Log injection possible. If readable, may contain credentials in logs."},
    {"port": 79, "proto": "TCP", "service": "Finger", "risk": "high",
     "tags": ["recon"],
     "desc": "Finger protocol — user information lookup. Leaks usernames and activity.",
     "tools": ["nmap"],
     "notes": "Enumerates logged-in users and home directories. Rarely seen now."},

    # ── BGP / RIP ────────────────────────────────────────────────────────────────
    {"port": 179, "proto": "TCP", "service": "BGP", "risk": "high",
     "tags": ["network", "routing"],
     "desc": "Border Gateway Protocol — internet routing protocol.",
     "tools": ["nmap"],
     "notes": "BGP hijacking if exposed. Quagga/BIRD misconfigs sometimes accept unauthenticated peers."},
    {"port": 520, "proto": "UDP", "service": "RIP", "risk": "high",
     "tags": ["network", "routing"],
     "desc": "Routing Information Protocol — legacy dynamic routing.",
     "tools": ["nmap"],
     "notes": "No authentication in RIPv1. Fake route injection trivial."},

    # ── IMAP / POP3 ─ (already above) ───────────────────────────────────────────

    # ── VPN / IPSec ──────────────────────────────────────────────────────────────
    {"port": 500, "proto": "UDP", "service": "IKE/IPSec", "risk": "med",
     "tags": ["vpn"],
     "desc": "Internet Key Exchange — used to set up IPSec VPN tunnels.",
     "tools": ["nmap"],
     "notes": "Enumerate IKE transforms with ike-scan. Aggressive mode can reveal PSK for offline crack."},
    {"port": 1194, "proto": "TCP/UDP", "service": "OpenVPN", "risk": "low",
     "tags": ["vpn"],
     "desc": "OpenVPN default port.",
     "tools": ["nmap"],
     "notes": "Confirm version. CVEs for specific OpenVPN versions (pre-auth DoS/RCE)."},
    {"port": 1723, "proto": "TCP", "service": "PPTP", "risk": "high",
     "tags": ["vpn"],
     "desc": "Point-to-Point Tunneling Protocol VPN. Cryptographically broken.",
     "tools": ["nmap"],
     "notes": "MS-CHAPv2 is trivially crackable. PPTP presence is itself a finding."},

    # ── Proxies ──────────────────────────────────────────────────────────────────
    {"port": 1080, "proto": "TCP", "service": "SOCKS Proxy", "risk": "high",
     "tags": ["proxy", "network"],
     "desc": "SOCKS proxy — often misconfigured as open proxy, enabling traffic pivoting.",
     "tools": ["nmap"],
     "notes": "Open SOCKS proxy allows full network pivoting through the server."},
    {"port": 3128, "proto": "TCP", "service": "Squid Proxy", "risk": "high",
     "tags": ["proxy", "web"],
     "desc": "Squid HTTP proxy default port.",
     "tools": ["nmap", "httpx"],
     "notes": "Open proxy: use CONNECT method to reach internal hosts. Check for auth bypass."},

    # ── Java / RMI ───────────────────────────────────────────────────────────────
    {"port": 1099, "proto": "TCP", "service": "Java RMI", "risk": "high",
     "tags": ["java", "rce"],
     "desc": "Java Remote Method Invocation registry.",
     "tools": ["nmap"],
     "notes": "Unauthenticated RMI registry = RCE via deserialization. Use ysoserial payload."},

    # ── Databases ────────────────────────────────────────────────────────────────
    {"port": 1433, "proto": "TCP", "service": "MSSQL", "risk": "high",
     "tags": ["database"],
     "desc": "Microsoft SQL Server — feature-rich DB with many lateral movement vectors.",
     "tools": ["nmap", "netexec", "sqlmap", "hydra"],
     "notes": "xp_cmdshell for RCE. Link servers for lateral movement. Spray SA/sa creds."},
    {"port": 1521, "proto": "TCP", "service": "Oracle DB", "risk": "high",
     "tags": ["database"],
     "desc": "Oracle Database listener.",
     "tools": ["nmap", "hydra"],
     "notes": "TNS poisoning. SID enumeration. Default creds (scott/tiger). Java execution for RCE."},
    {"port": 3306, "proto": "TCP", "service": "MySQL", "risk": "high",
     "tags": ["database"],
     "desc": "MySQL / MariaDB database server.",
     "tools": ["nmap", "hydra", "sqlmap"],
     "notes": "Check for remote root with empty password. INTO OUTFILE for file write / webshell."},
    {"port": 5432, "proto": "TCP", "service": "PostgreSQL", "risk": "high",
     "tags": ["database"],
     "desc": "PostgreSQL database server.",
     "tools": ["nmap", "hydra", "sqlmap"],
     "notes": "COPY TO/FROM for file read/write. COPY TO PROGRAM for RCE (pg >= 9.3 as superuser)."},
    {"port": 5984, "proto": "TCP", "service": "CouchDB", "risk": "high",
     "tags": ["database"],
     "desc": "Apache CouchDB — NoSQL HTTP API, often exposed without auth.",
     "tools": ["nmap", "httpx", "nuclei"],
     "notes": "Unauthenticated admin = RCE via query server (_query_server). CVE-2017-12635."},
    {"port": 6379, "proto": "TCP", "service": "Redis", "risk": "high",
     "tags": ["database", "messaging"],
     "desc": "Redis in-memory key-value store. No auth by default in older versions.",
     "tools": ["nmap", "nuclei"],
     "notes": "CONFIG SET dir + SAVE for SSH key write. Slave-of trick for RCE via module load."},
    {"port": 9200, "proto": "TCP", "service": "Elasticsearch HTTP", "risk": "high",
     "tags": ["database", "monitoring"],
     "desc": "Elasticsearch REST API. Often exposed without authentication.",
     "tools": ["nmap", "httpx", "nuclei"],
     "notes": "Unauthenticated: dump all indices. CVE-2014-3120 / CVE-2015-1427 for RCE via Groovy."},
    {"port": 9300, "proto": "TCP", "service": "Elasticsearch Cluster", "risk": "high",
     "tags": ["database"],
     "desc": "Elasticsearch cluster communication port.",
     "tools": ["nmap"],
     "notes": "Java deserialization RCE on cluster transport. Should never be internet-exposed."},
    {"port": 11211, "proto": "TCP/UDP", "service": "Memcached", "risk": "high",
     "tags": ["database", "messaging"],
     "desc": "Memcached — in-memory caching. No auth, often stores session tokens.",
     "tools": ["nmap"],
     "notes": "No auth: `stats`, `get` all keys. May contain session data, credentials, PII."},
    {"port": 27017, "proto": "TCP", "service": "MongoDB", "risk": "high",
     "tags": ["database"],
     "desc": "MongoDB database server. Default install has no authentication.",
     "tools": ["nmap", "nuclei"],
     "notes": "No auth: dump all databases instantly. Look for session and credential collections."},
    {"port": 27018, "proto": "TCP", "service": "MongoDB Shard", "risk": "high",
     "tags": ["database"],
     "desc": "MongoDB shard process port.",
     "tools": ["nmap"],
     "notes": "Same risks as 27017. Sharded cluster nodes."},

    # ── NFS / rsync ──────────────────────────────────────────────────────────────
    {"port": 2049, "proto": "TCP/UDP", "service": "NFS", "risk": "high",
     "tags": ["file-transfer"],
     "desc": "Network File System — remote filesystem mounting.",
     "tools": ["nmap"],
     "notes": "Enumerate exports with `showmount -e`. No_root_squash = file write as root."},
    {"port": 873, "proto": "TCP", "service": "rsync", "risk": "high",
     "tags": ["file-transfer"],
     "desc": "rsync daemon — often exposes modules without authentication.",
     "tools": ["nmap"],
     "notes": "`rsync rsync://<target>/` to list modules. May expose full filesystem."},

    # ── Remote Desktop / VNC ─────────────────────────────────────────────────────
    {"port": 3389, "proto": "TCP", "service": "RDP", "risk": "high",
     "tags": ["remote-access", "windows"],
     "desc": "Remote Desktop Protocol — Windows GUI remote access.",
     "tools": ["nmap", "netexec", "hydra"],
     "notes": "BlueKeep (CVE-2019-0708), DejaBlue. Credential spray. Check NLA enforcement."},
    {"port": 5900, "proto": "TCP", "service": "VNC", "risk": "high",
     "tags": ["remote-access"],
     "desc": "Virtual Network Computing — graphical remote access.",
     "tools": ["nmap", "hydra"],
     "notes": "Often no auth or weak password. Metasploit auxiliary/scanner/vnc/vnc_login."},

    # ── WinRM ────────────────────────────────────────────────────────────────────
    {"port": 5985, "proto": "TCP", "service": "WinRM HTTP", "risk": "high",
     "tags": ["remote-access", "windows", "active-directory"],
     "desc": "Windows Remote Management (HTTP) — PowerShell Remoting / evil-winrm.",
     "tools": ["nmap", "evil-winrm", "netexec"],
     "notes": "evil-winrm with creds or hash for shell. NetExec can enumerate without shell."},
    {"port": 5986, "proto": "TCP", "service": "WinRM HTTPS", "risk": "high",
     "tags": ["remote-access", "windows"],
     "desc": "WinRM over HTTPS — encrypted PowerShell Remoting.",
     "tools": ["nmap", "evil-winrm", "netexec"],
     "notes": "Same as 5985 but TLS. evil-winrm -S flag for SSL."},

    # ── Docker / Container ───────────────────────────────────────────────────────
    {"port": 2375, "proto": "TCP", "service": "Docker (Unauthenticated)", "risk": "high",
     "tags": ["container", "rce"],
     "desc": "Docker daemon REST API without TLS — direct container and host control.",
     "tools": ["nmap", "nuclei"],
     "notes": "Instant root: `docker run -v /:/mnt --rm -it alpine chroot /mnt`. Most critical finding."},
    {"port": 2376, "proto": "TCP", "service": "Docker TLS", "risk": "med",
     "tags": ["container"],
     "desc": "Docker daemon with TLS client certificate auth.",
     "tools": ["nmap"],
     "notes": "Check for cert-less access. Steal client certs from CI/CD systems."},
    {"port": 5000, "proto": "TCP", "service": "Docker Registry / Dev Server", "risk": "high",
     "tags": ["container", "web"],
     "desc": "Docker Registry (unauthenticated) or common dev server port (Flask, etc.).",
     "tools": ["nmap", "httpx", "nuclei"],
     "notes": "Unauthenticated registry: pull all images, extract secrets. Dev Flask: debug console RCE."},

    # ── Kubernetes ───────────────────────────────────────────────────────────────
    {"port": 6443, "proto": "TCP", "service": "Kubernetes API", "risk": "high",
     "tags": ["container", "cloud"],
     "desc": "Kubernetes API server — cluster control plane.",
     "tools": ["nmap", "nuclei"],
     "notes": "Check for anonymous access (`kubectl --insecure-skip-tls-verify`). Privileged pods = node escape."},
    {"port": 10250, "proto": "TCP", "service": "Kubelet API", "risk": "high",
     "tags": ["container", "cloud"],
     "desc": "Kubelet API — node agent. Can execute commands in pods.",
     "tools": ["nmap", "nuclei"],
     "notes": "Unauth kubelet: `GET /pods` for pod list, `POST /exec/<pod>` for RCE."},
    {"port": 10255, "proto": "TCP", "service": "Kubelet Read-Only", "risk": "med",
     "tags": ["container", "cloud"],
     "desc": "Kubelet read-only port — unauthenticated metadata exposure.",
     "tools": ["nmap", "httpx"],
     "notes": "Pod specs, env vars (including secrets). Deprecated in k8s 1.16+."},

    # ── etcd ─────────────────────────────────────────────────────────────────────
    {"port": 2379, "proto": "TCP", "service": "etcd Client", "risk": "high",
     "tags": ["cloud", "database"],
     "desc": "etcd key-value store — stores all Kubernetes secrets and config.",
     "tools": ["nmap"],
     "notes": "Unauthenticated etcd = dump all K8s secrets: `etcdctl get / --prefix`. Total cluster compromise."},
    {"port": 2380, "proto": "TCP", "service": "etcd Peer", "risk": "high",
     "tags": ["cloud"],
     "desc": "etcd peer-to-peer communication.",
     "tools": ["nmap"],
     "notes": "Joining etcd peer ring = full cluster state access."},

    # ── Prometheus / Grafana / Kibana ────────────────────────────────────────────
    {"port": 9090, "proto": "TCP", "service": "Prometheus", "risk": "high",
     "tags": ["monitoring", "web"],
     "desc": "Prometheus metrics server — no auth by default.",
     "tools": ["nmap", "httpx"],
     "notes": "Unauthenticated: scrape all metrics, target list reveals internal network topology."},
    {"port": 3000, "proto": "TCP", "service": "Grafana / Dev Server", "risk": "high",
     "tags": ["monitoring", "web"],
     "desc": "Grafana dashboards or common Node.js dev server port.",
     "tools": ["nmap", "httpx", "nuclei"],
     "notes": "Default admin:admin. CVE-2021-43798 (path traversal). Internal data sources visible."},
    {"port": 5601, "proto": "TCP", "service": "Kibana", "risk": "high",
     "tags": ["monitoring", "web"],
     "desc": "Kibana — Elasticsearch visualization. Often no auth in internal deployments.",
     "tools": ["nmap", "httpx", "nuclei"],
     "notes": "Unauthenticated: access all Elasticsearch data. CVE-2019-7609 (prototype pollution RCE)."},

    # ── App Servers ──────────────────────────────────────────────────────────────
    {"port": 7001, "proto": "TCP", "service": "WebLogic HTTP", "risk": "high",
     "tags": ["java", "web", "rce"],
     "desc": "Oracle WebLogic Server HTTP/HTTPS management.",
     "tools": ["nmap", "nuclei"],
     "notes": "OGNL injection, Java deserialization chain. CVE-2020-14882 (unauth admin). High value target."},
    {"port": 7070, "proto": "TCP", "service": "WebLogic IIOP", "risk": "high",
     "tags": ["java", "rce"],
     "desc": "WebLogic IIOP/T3 protocol — Java deserialization attack vector.",
     "tools": ["nmap"],
     "notes": "T3 deserialization: ysoserial with CommonsCollections chain = unauthenticated RCE."},
    {"port": 9000, "proto": "TCP", "service": "PHP-FPM / Portainer", "risk": "high",
     "tags": ["web", "container"],
     "desc": "PHP FastCGI Process Manager or Portainer Docker UI.",
     "tools": ["nmap", "httpx", "nuclei"],
     "notes": "Exposed PHP-FPM: Fastcgi exploit for RCE. Portainer: default admin or API misconfig."},

    # ── ICS / SCADA ──────────────────────────────────────────────────────────────
    {"port": 502, "proto": "TCP", "service": "Modbus", "risk": "high",
     "tags": ["ics"],
     "desc": "Modbus TCP — ICS/SCADA protocol, no authentication whatsoever.",
     "tools": ["nmap"],
     "notes": "Read/write coils and registers with no auth. Physical impact possible on OT networks."},
    {"port": 623, "proto": "UDP", "service": "IPMI", "risk": "high",
     "tags": ["network", "remote-access"],
     "desc": "Intelligent Platform Management Interface — out-of-band server management.",
     "tools": ["nmap"],
     "notes": "IPMI 2.0 RAKP flaw: retrieve password hash offline. Default creds (ADMIN/ADMIN)."},

    # ── RTSP / SIP ───────────────────────────────────────────────────────────────
    {"port": 554, "proto": "TCP/UDP", "service": "RTSP", "risk": "high",
     "tags": ["media", "iot"],
     "desc": "Real-Time Streaming Protocol — IP cameras and media servers.",
     "tools": ["nmap"],
     "notes": "IP camera streams often default-credential protected. Try admin:admin, admin:12345."},

    # ── Version Control ──────────────────────────────────────────────────────────
    {"port": 3690, "proto": "TCP", "service": "SVN", "risk": "med",
     "tags": ["version-control"],
     "desc": "Apache Subversion — source control.",
     "tools": ["nmap"],
     "notes": "Anonymous checkout may expose source code. Check `svn ls svn://<target>`."},

    # ── VMware ───────────────────────────────────────────────────────────────────
    {"port": 902, "proto": "TCP", "service": "VMware", "risk": "high",
     "tags": ["virtualization"],
     "desc": "VMware ESXi/Workstation remote access and authentication.",
     "tools": ["nmap"],
     "notes": "Enumerate VMware version. ESXi SLP CVE-2021-21985. Remote console access."},

    # ── Salt ─────────────────────────────────────────────────────────────────────
    {"port": 4505, "proto": "TCP", "service": "SaltStack Master", "risk": "high",
     "tags": ["cloud", "rce"],
     "desc": "SaltStack master publish port — commands sent to minions.",
     "tools": ["nmap"],
     "notes": "CVE-2020-11651/11652: unauth RCE on master. Exploiting = command exec on all minions."},
    {"port": 4506, "proto": "TCP", "service": "SaltStack Return", "risk": "high",
     "tags": ["cloud"],
     "desc": "SaltStack minion return channel.",
     "tools": ["nmap"],
     "notes": "Part of same Salt attack surface as 4505."},

    # ── SAP ──────────────────────────────────────────────────────────────────────
    {"port": 50000, "proto": "TCP", "service": "SAP Message Server HTTP", "risk": "high",
     "tags": ["web", "database"],
     "desc": "SAP NetWeaver message server HTTP port.",
     "tools": ["nmap", "httpx"],
     "notes": "RECON CVE-2020-6287: unauthenticated admin user creation. Critical SAP vulnerability."},

    # ── Messaging ────────────────────────────────────────────────────────────────
    {"port": 5672, "proto": "TCP", "service": "AMQP", "risk": "med",
     "tags": ["messaging"],
     "desc": "Advanced Message Queuing Protocol — RabbitMQ default.",
     "tools": ["nmap", "hydra"],
     "notes": "Default guest:guest creds often work. Access to message queues may expose sensitive data."},
    {"port": 1883, "proto": "TCP", "service": "MQTT", "risk": "high",
     "tags": ["messaging", "iot"],
     "desc": "MQTT broker — IoT messaging protocol, often no auth.",
     "tools": ["nmap"],
     "notes": "No auth: subscribe to # wildcard topic to receive all messages. IoT telemetry exposure."},

    # ── rsh / rexec ─────────────────────────────────────────────────────────────
    {"port": 512, "proto": "TCP", "service": "rexec", "risk": "high",
     "tags": ["remote-access"],
     "desc": "Remote execution (rexec) — legacy cleartext remote command execution.",
     "tools": ["nmap"],
     "notes": "Plaintext credentials. Check .rhosts for trust relationships. Rarely seen but critical when found."},
    {"port": 513, "proto": "TCP", "service": "rlogin", "risk": "high",
     "tags": ["remote-access"],
     "desc": "Remote login — legacy trust-based auth via .rhosts.",
     "tools": ["nmap"],
     "notes": ".rhosts with `+ +` allows unauthenticated access. Check trusted hosts."},
    {"port": 515, "proto": "TCP", "service": "LPD", "risk": "med",
     "tags": ["network"],
     "desc": "Line Printer Daemon — legacy print server.",
     "tools": ["nmap"],
     "notes": "Old exploits (CVE-1999-0061). Sometimes exposes file read via lpr."},

    # ── IRC ──────────────────────────────────────────────────────────────────────
    {"port": 194, "proto": "TCP", "service": "IRC", "risk": "low",
     "tags": ["messaging"],
     "desc": "Internet Relay Chat — legacy chat protocol.",
     "tools": ["nmap"],
     "notes": "Botnet C2 channels often use IRC. May indicate compromised host."},

    # ── Metasploit ───────────────────────────────────────────────────────────────
    {"port": 4444, "proto": "TCP", "service": "Metasploit Default", "risk": "high",
     "tags": ["pentest"],
     "desc": "Default Metasploit meterpreter listener port. Indicates active engagement or C2.",
     "tools": ["nmap", "msfconsole"],
     "notes": "Your listener port. Configure with `use exploit/multi/handler`. Remember to set LPORT."},
]

# Index by port number for O(1) lookup
PORTS_BY_NUMBER = {p["port"]: p for p in PORTS}
