"""Network protocol reference data for /reference/protocols."""

PROTOCOLS = [
    # ── Layer 2 ───────────────────────────────────────────────────────────────
    {
        "name": "ARP", "full": "Address Resolution Protocol",
        "layer": 2, "port": None, "category": "Layer 2",
        "desc": "Maps IP addresses to MAC addresses on a local network segment. Stateless — any host can send unsolicited ARP replies.",
        "attacks": ["ARP spoofing / poisoning", "Man-in-the-middle via gratuitous ARP", "ARP cache flooding"],
        "detect": ["Unexpected ARP replies", "Multiple MACs for same IP", "Gratuitous ARPs from unknown hosts"],
        "tools": ["arpwatch", "hping3", "scapy", "nmap"],
        "rfc": "RFC 826",
    },
    {
        "name": "Ethernet", "full": "IEEE 802.3",
        "layer": 2, "port": None, "category": "Layer 2",
        "desc": "Dominant wired LAN protocol. Frames carry a 6-byte source and destination MAC address plus a 2-byte EtherType.",
        "attacks": ["MAC flooding (CAM table overflow)", "VLAN hopping (double tagging)", "MAC spoofing"],
        "detect": ["Port security violations", "Unusual EtherType values", "MAC address changes"],
        "tools": ["scapy", "tcpdump", "tshark"],
        "rfc": "IEEE 802.3",
    },
    {
        "name": "802.11", "full": "IEEE 802.11 (Wi-Fi)",
        "layer": 2, "port": None, "category": "Layer 2",
        "desc": "Wireless LAN standard. Management frames (probe, auth, assoc, beacon) are unauthenticated in open and WPA2-Personal networks.",
        "attacks": ["Deauth/disassoc floods", "Evil twin AP", "PMKID capture", "KRACK (WPA2)", "WPS PIN brute force"],
        "detect": ["Deauth storms", "BSSID conflicts", "Unexpected probe responses"],
        "tools": ["aircrack-ng", "hcxtools", "wireshark", "kismet"],
        "rfc": "IEEE 802.11",
    },
    # ── Layer 3 ───────────────────────────────────────────────────────────────
    {
        "name": "IP", "full": "Internet Protocol v4",
        "layer": 3, "port": None, "category": "Layer 3",
        "desc": "Connectionless packet delivery. 20-byte header includes TTL, protocol number, and 32-bit src/dst addresses. No built-in authentication.",
        "attacks": ["IP spoofing", "Fragmentation attacks (teardrop, overlapping frags)", "TTL-based evasion"],
        "detect": ["Source IP outside expected ranges", "Unusual TTL values", "Malformed fragments"],
        "tools": ["scapy", "hping3", "nmap"],
        "rfc": "RFC 791",
    },
    {
        "name": "IPv6", "full": "Internet Protocol v6",
        "layer": 3, "port": None, "category": "Layer 3",
        "desc": "128-bit addressing, mandatory extension headers, and built-in ICMPv6 for neighbor discovery. Many networks have IPv6 enabled but unmonitored.",
        "attacks": ["Rogue RA (Router Advertisement)", "SLAAC abuse", "NDP spoofing", "IPv6 tunnel evasion"],
        "detect": ["Unexpected RAs", "Dual-stack blind spots in firewall rules", "6to4/Teredo tunnels"],
        "tools": ["scapy", "nmap -6", "thc-ipv6"],
        "rfc": "RFC 8200",
    },
    {
        "name": "ICMP", "full": "Internet Control Message Protocol",
        "layer": 3, "port": None, "category": "Layer 3",
        "desc": "Error and diagnostic messages for IP. Type 8 = Echo Request (ping), Type 0 = Echo Reply. Widely used for network recon.",
        "attacks": ["ICMP redirect injection", "ICMP tunneling (covert C2)", "Ping of death", "Smurf amplification"],
        "detect": ["Unusually large ICMP payloads (>64 bytes)", "High ICMP volume from single source", "ICMP type 5 (redirect)"],
        "tools": ["ping", "hping3 --icmp", "scapy", "nmap -PE"],
        "rfc": "RFC 792",
    },
    {
        "name": "OSPF", "full": "Open Shortest Path First",
        "layer": 3, "port": None, "category": "Routing",
        "desc": "Link-state routing protocol. Routers exchange LSAs to build a topology map. Uses IP protocol 89 (not TCP/UDP).",
        "attacks": ["Rogue router injection", "LSA spoofing to manipulate routes", "OSPF neighbor spoofing"],
        "detect": ["Unexpected OSPF adjacencies", "Route changes not initiated by admins"],
        "tools": ["scapy", "quagga", "wireshark"],
        "rfc": "RFC 2328",
    },
    {
        "name": "BGP", "full": "Border Gateway Protocol",
        "layer": 3, "port": 179, "category": "Routing",
        "desc": "The routing protocol of the internet. Runs over TCP port 179. Controls inter-AS route advertisement — prefix hijacking can redirect global traffic.",
        "attacks": ["BGP prefix hijacking", "Route leak", "BGP session reset (TCP RST injection)", "MITM via rogue AS"],
        "detect": ["Unexpected OPEN messages", "New prefixes from known AS", "Route origin validation failures"],
        "tools": ["bgpdump", "scapy", "wireshark"],
        "rfc": "RFC 4271",
    },
    # ── Layer 4 ───────────────────────────────────────────────────────────────
    {
        "name": "TCP", "full": "Transmission Control Protocol",
        "layer": 4, "port": None, "category": "Layer 4",
        "desc": "Reliable, ordered, connection-oriented transport. 3-way handshake (SYN→SYN-ACK→ACK). Flags: SYN, ACK, FIN, RST, PSH, URG.",
        "attacks": ["SYN flood", "TCP session hijacking", "RST injection", "Half-open scan (SYN stealth)"],
        "detect": ["SYN without ACK storm", "RST floods", "Unexpected sequence numbers"],
        "tools": ["nmap -sS", "hping3 -S", "scapy", "tcpdump"],
        "rfc": "RFC 9293",
    },
    {
        "name": "UDP", "full": "User Datagram Protocol",
        "layer": 4, "port": None, "category": "Layer 4",
        "desc": "Connectionless, unordered transport. Minimal overhead. Used by DNS, NTP, DHCP, QUIC, VoIP. No handshake means harder to filter.",
        "attacks": ["UDP flood", "Amplification attacks (DNS, NTP, SSDP)", "UDP port scan"],
        "detect": ["High-rate UDP to unusual ports", "Large UDP responses vs small requests (amplification ratio)"],
        "tools": ["nmap -sU", "hping3 --udp", "scapy"],
        "rfc": "RFC 768",
    },
    # ── Application layer ─────────────────────────────────────────────────────
    {
        "name": "HTTP", "full": "Hypertext Transfer Protocol",
        "layer": 7, "port": 80, "category": "Web",
        "desc": "Plaintext application-layer protocol for web. Request methods: GET, POST, PUT, DELETE, OPTIONS, TRACE. Headers are attacker-controlled.",
        "attacks": ["SQL injection", "XSS", "SSRF", "HTTP smuggling", "Host header injection", "CORS abuse", "Path traversal"],
        "detect": ["Unusual HTTP methods (TRACE/CONNECT)", "Encoded payloads in URI", "Anomalous User-Agent"],
        "tools": ["ffuf", "nuclei", "sqlmap", "dalfox", "smuggler", "nikto"],
        "rfc": "RFC 9110",
    },
    {
        "name": "HTTPS", "full": "HTTP over TLS",
        "layer": 7, "port": 443, "category": "Web",
        "desc": "HTTP encrypted with TLS. Certificates bind identity to public key. TLS 1.2/1.3 are current; older versions (TLS 1.0, SSLv3) are vulnerable.",
        "attacks": ["TLS downgrade (POODLE, BEAST)", "Certificate forgery", "MITM with rogue CA", "SNI inspection bypass"],
        "detect": ["Self-signed or expired certs", "Weak cipher suites (RC4, 3DES)", "Certificate pinning bypass attempts"],
        "tools": ["testssl", "sslyze", "sslscan", "nuclei"],
        "rfc": "RFC 8446 (TLS 1.3)",
    },
    {
        "name": "DNS", "full": "Domain Name System",
        "layer": 7, "port": 53, "category": "Infrastructure",
        "desc": "Maps hostnames to IP addresses. Uses UDP (small queries) and TCP (large responses, zone transfers). Cache poisoning remains a major risk.",
        "attacks": ["DNS cache poisoning", "DNS zone transfer (AXFR)", "DNS tunneling (C2 exfil)", "Subdomain takeover", "DNS rebinding"],
        "detect": ["Large DNS responses over UDP", "AXFR requests from non-authoritative sources", "High-entropy subdomains (DGA/tunneling)"],
        "tools": ["dnsx", "dig", "dnsrecon", "fierce", "massdns"],
        "rfc": "RFC 1035",
    },
    {
        "name": "FTP", "full": "File Transfer Protocol",
        "layer": 7, "port": 21, "category": "File Transfer",
        "desc": "Plaintext file transfer. Control channel on 21, data channel on 20 (active) or ephemeral port (passive). Credentials sent in cleartext.",
        "attacks": ["Credential brute force", "Anonymous login", "FTP bounce scan", "Cleartext credential sniffing"],
        "detect": ["Anonymous login attempts", "SITE EXEC commands", "Port/PASV commands from external IPs"],
        "tools": ["hydra", "medusa", "nmap --script ftp-*", "nc"],
        "rfc": "RFC 959",
    },
    {
        "name": "SSH", "full": "Secure Shell",
        "layer": 7, "port": 22, "category": "Remote Access",
        "desc": "Encrypted remote shell, SCP, and SFTP. Key exchange negotiates cipher and HMAC. Vulnerable to weak algorithms and key management failures.",
        "attacks": ["Password/key brute force", "Weak host key algorithms (RSA-1024)", "SSH tunneling for exfiltration", "Agent forwarding abuse"],
        "detect": ["Failed auth bursts", "Logins from unusual geos", "Large data transfers over SSH"],
        "tools": ["ssh", "hydra", "nmap --script ssh-*", "nc"],
        "rfc": "RFC 4253",
    },
    {
        "name": "Telnet", "full": "Telnet",
        "layer": 7, "port": 23, "category": "Remote Access",
        "desc": "Plaintext remote terminal protocol. Completely insecure — credentials and session data transmitted in cleartext. Should never be used in production.",
        "attacks": ["Credential sniffing", "Session hijacking", "Brute force"],
        "detect": ["Any Telnet traffic (should be blocked)", "Login banners in cleartext"],
        "tools": ["nc", "hydra", "nmap -sV"],
        "rfc": "RFC 854",
    },
    {
        "name": "SMTP", "full": "Simple Mail Transfer Protocol",
        "layer": 7, "port": 25, "category": "Email",
        "desc": "Mail transfer between servers. Port 25 for server-to-server; 587 (STARTTLS) for submission. Open relays allow spam and phishing.",
        "attacks": ["Open relay abuse", "VRFY/EXPN user enumeration", "Mail spoofing (SPF/DKIM/DMARC bypass)", "SMTP injection"],
        "detect": ["VRFY/EXPN commands", "Relaying from unauthenticated hosts", "RCPT TO bulk enumeration"],
        "tools": ["nmap --script smtp-*", "swaks", "nc"],
        "rfc": "RFC 5321",
    },
    {
        "name": "IMAP", "full": "Internet Message Access Protocol",
        "layer": 7, "port": 143, "category": "Email",
        "desc": "Email access protocol. Port 143 (plaintext), 993 (TLS). Supports folder management and partial fetch. Credentials reusable across services.",
        "attacks": ["Password spraying", "Credential brute force", "Cleartext sniffing on port 143"],
        "detect": ["Auth failures across multiple accounts", "Logins from unusual IPs"],
        "tools": ["hydra", "medusa"],
        "rfc": "RFC 9051",
    },
    {
        "name": "POP3", "full": "Post Office Protocol v3",
        "layer": 7, "port": 110, "category": "Email",
        "desc": "Simple email retrieval. Port 110 (plaintext), 995 (TLS). Downloads and deletes from server. Largely superseded by IMAP.",
        "attacks": ["Credential brute force", "Plaintext credential sniffing on port 110"],
        "detect": ["Auth bursts", "Plaintext POP3 traffic on monitored networks"],
        "tools": ["hydra", "nc"],
        "rfc": "RFC 1939",
    },
    {
        "name": "SMB", "full": "Server Message Block / CIFS",
        "layer": 7, "port": 445, "category": "Windows / AD",
        "desc": "Windows file sharing and authentication. Port 445 (direct). Notorious for remote exploits (EternalBlue/MS17-010, PrintNightmare). Central to AD lateral movement.",
        "attacks": ["EternalBlue (MS17-010)", "Pass-the-hash", "Relay attacks (NTLM relay)", "PrintNightmare", "Share enumeration"],
        "detect": ["IPC$ connections from unexpected hosts", "Named pipe access", "SMB1 negotiation"],
        "tools": ["netexec", "enum4linux-ng", "nmap --script smb-*", "impacket"],
        "rfc": "MS-SMB2",
    },
    {
        "name": "RDP", "full": "Remote Desktop Protocol",
        "layer": 7, "port": 3389, "category": "Windows / AD",
        "desc": "Microsoft graphical remote access. Uses NLA by default. BlueKeep (CVE-2019-0708) and DejaBlue enable pre-auth RCE. Widely targeted by ransomware.",
        "attacks": ["BlueKeep (CVE-2019-0708)", "Credential brute force", "Pass-the-hash with Restricted Admin", "RDP MITM"],
        "detect": ["External RDP exposure", "Auth failures", "RDP from unusual source IPs"],
        "tools": ["nmap --script rdp-*", "hydra", "nuclei"],
        "rfc": "MS-RDPBCGR",
    },
    {
        "name": "LDAP", "full": "Lightweight Directory Access Protocol",
        "layer": 7, "port": 389, "category": "Windows / AD",
        "desc": "Directory service protocol. Port 389 (plaintext), 636 (LDAPS). Core of Active Directory — used for auth, user/group queries, and policy lookups.",
        "attacks": ["LDAP injection", "Anonymous bind (null base DN)", "Credential dumping via LDAP queries", "BloodHound data collection"],
        "detect": ["Anonymous binds", "Large LDAP dumps from non-DC hosts", "Unusual attribute queries"],
        "tools": ["bloodhound-py", "ldapsearch", "netexec", "enum4linux-ng"],
        "rfc": "RFC 4511",
    },
    {
        "name": "Kerberos", "full": "Kerberos v5",
        "layer": 7, "port": 88, "category": "Windows / AD",
        "desc": "Ticket-based auth used by Active Directory. AS-REQ/TGT → TGS-REQ/service ticket. Tickets are cryptographically signed but offline-crackable if weak encryption is used.",
        "attacks": ["Kerberoasting (SPN ticket cracking)", "AS-REP Roasting (no pre-auth accounts)", "Pass-the-ticket", "Golden/Silver ticket", "Overpass-the-hash"],
        "detect": ["AS-REQ without pre-auth (RC4 tickets)", "Unusual TGS requests for service accounts", "TGT lifetime anomalies"],
        "tools": ["kerbrute", "getuserspns", "impacket", "rubeus"],
        "rfc": "RFC 4120",
    },
    {
        "name": "SNMP", "full": "Simple Network Management Protocol",
        "layer": 7, "port": 161, "category": "Infrastructure",
        "desc": "Network device management. v1/v2c use plaintext community strings ('public'/'private'). SNMPv3 adds auth and encryption but is rarely deployed.",
        "attacks": ["Default community string access", "MIB enumeration (network topology, ARP tables)", "SNMP write (configuration change)", "Amplification DDoS"],
        "detect": ["SNMP GET/WALK from unexpected hosts", "SNMP write operations", "Community string in cleartext"],
        "tools": ["nmap --script snmp-*", "snmpwalk", "onesixtyone"],
        "rfc": "RFC 3411",
    },
    {
        "name": "NTP", "full": "Network Time Protocol",
        "layer": 7, "port": 123, "category": "Infrastructure",
        "desc": "Time synchronization over UDP. Mode 6/7 (monlist) commands expose peer lists and can be abused for amplification attacks.",
        "attacks": ["NTP amplification DDoS (monlist)", "Time skew attack (Kerberos 5-min window)", "NTP MITM"],
        "detect": ["Monlist (mode 6) queries from external IPs", "NTP responses > 500 bytes to small queries"],
        "tools": ["nmap --script ntp-*", "ntpq", "scapy"],
        "rfc": "RFC 5905",
    },
    {
        "name": "DHCP", "full": "Dynamic Host Configuration Protocol",
        "layer": 7, "port": 67, "category": "Infrastructure",
        "desc": "Automatically assigns IP, gateway, DNS. DORA: Discover→Offer→Request→ACK. No authentication — any host can respond as a DHCP server.",
        "attacks": ["Rogue DHCP server (gateway/DNS redirect)", "DHCP starvation (exhaust IP pool)", "DHCP option 43/66 abuse"],
        "detect": ["Multiple DHCP OFFERs to same client", "DHCP from unexpected server MAC", "Pool exhaustion events"],
        "tools": ["scapy", "dhcpstarv", "wireshark"],
        "rfc": "RFC 2131",
    },
    {
        "name": "NetBIOS", "full": "Network Basic Input/Output System",
        "layer": 7, "port": 137, "category": "Windows / AD",
        "desc": "Legacy Windows name resolution and session service. Ports 137 (UDP/TCP name), 138 (UDP datagram), 139 (TCP session). Poisonable via Responder.",
        "attacks": ["NBNS poisoning (Responder)", "NetBIOS name spoofing", "SMB relay via NetBIOS"],
        "detect": ["NBNS requests from unusual hosts", "Responder-style broadcast responses"],
        "tools": ["responder", "nmap", "wireshark"],
        "rfc": "RFC 1001/1002",
    },
    {
        "name": "LLMNR", "full": "Link-Local Multicast Name Resolution",
        "layer": 7, "port": 5355, "category": "Windows / AD",
        "desc": "Fallback Windows name resolution multicast on UDP/TCP 5355. No authentication. Responder captures NTLMv2 hashes by responding to broadcast queries.",
        "attacks": ["LLMNR poisoning (Responder)", "NTLMv2 hash capture → relay or crack"],
        "detect": ["LLMNR queries for non-existent hosts", "Unexpected responses to multicast queries"],
        "tools": ["responder", "inveigh", "wireshark"],
        "rfc": "RFC 4795",
    },
    {
        "name": "mDNS", "full": "Multicast DNS",
        "layer": 7, "port": 5353, "category": "Infrastructure",
        "desc": "Zero-conf name resolution for .local domains. Multicast to 224.0.0.251:5353. Used by Bonjour, Avahi, Chromecast. Spoofable on local networks.",
        "attacks": ["mDNS poisoning", "Service discovery enumeration", "Apple device fingerprinting"],
        "detect": ["Responses to .local queries from unexpected hosts", "mDNS from routed (non-local) sources"],
        "tools": ["responder", "avahi-browse", "wireshark"],
        "rfc": "RFC 6762",
    },
    {
        "name": "WinRM", "full": "Windows Remote Management",
        "layer": 7, "port": 5985, "category": "Windows / AD",
        "desc": "Microsoft's implementation of WS-Management. HTTP on 5985, HTTPS on 5986. Used by PowerShell remoting and Evil-WinRM for lateral movement.",
        "attacks": ["Credential brute force", "Pass-the-hash", "Lateral movement via Evil-WinRM"],
        "detect": ["WinRM from non-admin hosts", "Failed auth attempts", "PowerShell remoting sessions"],
        "tools": ["evil-winrm", "netexec", "nmap"],
        "rfc": "MS-WSMV",
    },
    {
        "name": "RPC", "full": "MS-RPC / DCE-RPC",
        "layer": 7, "port": 135, "category": "Windows / AD",
        "desc": "Microsoft Remote Procedure Call endpoint mapper on port 135. Assigns dynamic ports for DCOM, WMI, Exchange, and other Windows services.",
        "attacks": ["DCOM lateral movement", "WMI exec via RPC", "DCE/RPC enumeration (endpoints, users)", "PetitPotam (EFSRPC)"],
        "detect": ["DCOM connections from unexpected hosts", "RPC endpoint mapper scans", "EFS calls to DC"],
        "tools": ["nmap --script msrpc-*", "impacket", "netexec"],
        "rfc": "MS-RPCE",
    },
    {
        "name": "RADIUS", "full": "Remote Authentication Dial-In User Service",
        "layer": 7, "port": 1812, "category": "Authentication",
        "desc": "AAA protocol for network access (VPN, Wi-Fi 802.1X, switch auth). UDP port 1812 (auth), 1813 (accounting). Shared secret is MD5-hashed — weak.",
        "attacks": ["Shared secret brute force", "EAP downgrade (LEAP, MD5-CHAP)", "Replay attacks (no sequence numbers)"],
        "detect": ["Auth failures from unusual NAS IPs", "Weak EAP types in use"],
        "tools": ["freeradius", "eaphammer", "wireshark"],
        "rfc": "RFC 2865",
    },
    {
        "name": "SYSLOG", "full": "Syslog",
        "layer": 7, "port": 514, "category": "Monitoring",
        "desc": "Standard log transport. UDP 514 (classic), TCP 514 or TLS 6514. No authentication in UDP mode — log injection and silencing are trivial.",
        "attacks": ["Log injection (forge events)", "Log suppression (flood to fill buffer)", "Plaintext credential sniffing"],
        "detect": ["Log gaps (silencing)", "Events from unexpected source IPs", "Malformed syslog messages"],
        "tools": ["nc", "logger", "scapy"],
        "rfc": "RFC 5424",
    },
    {
        "name": "TLS", "full": "Transport Layer Security",
        "layer": 6, "port": None, "category": "Encryption",
        "desc": "Cryptographic protocol securing TCP connections. TLS 1.3 (current), TLS 1.2 (acceptable), TLS 1.0/SSL deprecated. Handshake negotiates cipher suite, exchanges keys via asymmetric crypto.",
        "attacks": ["POODLE (SSLv3 padding oracle)", "BEAST (TLS 1.0 CBC)", "LUCKY13", "DROWN (SSLv2)", "Weak cipher suites (RC4, EXPORT)", "Downgrade attacks"],
        "detect": ["TLS version < 1.2", "NULL or EXPORT ciphers", "Self-signed or expired certificates"],
        "tools": ["testssl", "sslyze", "sslscan", "tlsx"],
        "rfc": "RFC 8446",
    },
]

CATEGORIES = sorted({p["category"] for p in PROTOCOLS})
