"""Export scan results as STIX 2.1 bundle or ATT&CK Navigator layer JSON."""
import uuid
from datetime import datetime, timezone
from typing import Any, Dict, List


def _now() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def to_stix_bundle(scan: Dict) -> Dict:
    findings = scan.get("findings", [])
    metrics  = scan.get("metrics", {})
    iocs     = metrics.get("ioc_summary", {})
    hashes   = metrics.get("file_hashes", [])
    now      = _now()
    objects: List[Dict[str, Any]] = []

    # Identity (this tool)
    identity_id = f"identity--{uuid.uuid4()}"
    objects.append({
        "type": "identity",
        "spec_version": "2.1",
        "id": identity_id,
        "created": now, "modified": now,
        "name": "Multiblade",
        "identity_class": "tool",
    })

    # Malware object when unsafe
    mal_id = None
    if not scan.get("safe", True):
        mal_id = f"malware--{uuid.uuid4()}"
        objects.append({
            "type": "malware",
            "spec_version": "2.1",
            "id": mal_id,
            "created": now, "modified": now,
            "name": f"Suspicious archive: {scan.get('filename', 'unknown')}",
            "is_family": False,
            "malware_types": ["unknown"],
            "description": (
                f"Risk score {metrics.get('risk_score', 0)}/100 "
                f"({metrics.get('risk_label', '')}). "
                f"{len(findings)} finding(s)."
            ),
        })

    # IP indicators
    for ip_obj in iocs.get("ips", []):
        if ip_obj.get("type") != "public":
            continue
        ind_id = f"indicator--{uuid.uuid4()}"
        objects.append({
            "type": "indicator",
            "spec_version": "2.1",
            "id": ind_id,
            "created": now, "modified": now,
            "name": f"IPv4: {ip_obj['ip']}",
            "indicator_types": ["malicious-activity"],
            "pattern": f"[ipv4-addr:value = '{ip_obj['ip']}']",
            "pattern_type": "stix",
            "valid_from": now,
        })
        if mal_id:
            objects.append({
                "type": "relationship",
                "spec_version": "2.1",
                "id": f"relationship--{uuid.uuid4()}",
                "created": now, "modified": now,
                "relationship_type": "indicates",
                "source_ref": ind_id,
                "target_ref": mal_id,
            })

    # URL indicators
    for url in iocs.get("urls", [])[:20]:
        safe_url = url[:500].replace("'", "\\'")
        ind_id = f"indicator--{uuid.uuid4()}"
        objects.append({
            "type": "indicator",
            "spec_version": "2.1",
            "id": ind_id,
            "created": now, "modified": now,
            "name": f"URL: {url[:80]}",
            "indicator_types": ["malicious-activity"],
            "pattern": f"[url:value = '{safe_url}']",
            "pattern_type": "stix",
            "valid_from": now,
        })

    # File hash indicators
    for h in hashes[:20]:
        ind_id = f"indicator--{uuid.uuid4()}"
        objects.append({
            "type": "indicator",
            "spec_version": "2.1",
            "id": ind_id,
            "created": now, "modified": now,
            "name": f"File: {h.get('filename', 'unknown')}",
            "indicator_types": ["malicious-activity"],
            "pattern": f"[file:hashes.'SHA-256' = '{h['sha256']}']",
            "pattern_type": "stix",
            "valid_from": now,
        })

    return {
        "type": "bundle",
        "id": f"bundle--{uuid.uuid4()}",
        "spec_version": "2.1",
        "objects": objects,
    }


def to_navigator_layer(scan: Dict) -> Dict:
    metrics    = scan.get("metrics", {})
    techniques = metrics.get("mitre_techniques", [])

    layer_techniques = []
    for t in techniques:
        layer_techniques.append({
            "techniqueID": t["id"],
            "score": 1,
            "color": "#6366f1",
            "comment": t.get("name", ""),
            "enabled": True,
            "showSubtechniques": False,
        })

    return {
        "name": f"Multiblade — {scan.get('filename', 'unknown')}",
        "versions": {"attack": "14", "navigator": "4.9.5", "layer": "4.5"},
        "domain": "enterprise-attack",
        "description": (
            f"Auto-generated by Multiblade. "
            f"Risk score: {metrics.get('risk_score', 0)}/100 ({metrics.get('risk_label', '')})."
        ),
        "filters": {"platforms": ["Windows", "macOS", "Linux"]},
        "sorting": 0,
        "layout": {"layout": "side", "showID": True, "showName": True},
        "hideDisabled": False,
        "techniques": layer_techniques,
        "gradient": {
            "colors": ["#dde1f520", "#6366f1"],
            "minValue": 0,
            "maxValue": 1,
        },
        "legendItems": [{"label": "Detected technique", "color": "#6366f1"}],
    }
